# Generated by Django 2.2.2 on 2019-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('scholar_no', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=1)),
                ('branch', models.CharField(max_length=3)),
            ],
        ),
    ]
